import 'dart:async';
import 'dart:io';
import 'dart:math' as math;

import 'package:flutter/foundation.dart';
import 'package:flutter/services.dart';

import '../../config/constants.dart';
import '../bridge/call_bridge_service.dart';
import '../gemini/gemini_live_client.dart';

/// Audio the caller hears when the agent cannot speak.
///
/// Two situations, both of which currently leave a real person listening to
/// nothing:
///
///  - **The data link dies mid-call.** Voice and data are separate paths, so
///    the carrier call survives while Gemini does not. The watchdog reconnects,
///    but if the link is genuinely gone it keeps failing and the caller sits in
///    silence. We cannot synthesise a reply without the network — so the lines
///    are generated *while the network is good* and cached.
///  - **A hand-over is being offered.** Fifteen seconds of dead air is exactly
///    when someone hangs up. Call centres play music for a reason.
///
/// The speech is generated by Gemini in the agent's own voice, so the apology
/// does not arrive in a different one. The hold loop is synthesised here in
/// Dart: it has to exist before the first successful connection, it has to loop
/// seamlessly, and generating it avoids licensing entirely.
class FallbackAudio {
  FallbackAudio({required this.bridge});

  final CallBridgeService bridge;

  static const _channel = MethodChannel('ai.fox1/call_bridge');

  /// PCM16 mono at 16 kHz — the rate the call runs at, so no resampling on the
  /// way out.
  static const _rate = 16000;

  /// One 60 ms frame, matching the board's cadence.
  static const _frameBytes = 1920;

  static const holdingLine =
      "One moment — I'm having trouble with my connection.";
  static const apologyLine =
      "I'm very sorry, I can't hear you properly. He'll call you back.";

  Uint8List? _holding;
  Uint8List? _apology;
  Uint8List? _music;

  Uint8List get holding => _holding ?? Uint8List(0);
  Uint8List get apology => _apology ?? Uint8List(0);
  Uint8List get music => _music ??= _synthesiseHoldMusic();

  bool get ready => _holding != null && _apology != null;

  // ------------------------------------------------------------- generation

  /// Load the cached clips, generating any that are missing.
  ///
  /// Called when a session opens — i.e. when the network is demonstrably
  /// working — rather than at the moment they are needed, which is by
  /// definition the moment the network is not.
  Future<void> ensureClips(GeminiConfig config) async {
    final dir = await _dir();
    if (dir == null) return;
    _holding = await _load(dir, 'holding', config, holdingLine);
    _apology = await _load(dir, 'apology', config, apologyLine);
    debugPrint('[FALLBACK] clips ${ready ? "ready" : "UNAVAILABLE"}'
        ' (holding ${_holding?.length ?? 0}B, apology ${_apology?.length ?? 0}B)');
  }

  Future<Uint8List?> _load(
    String dir,
    String name,
    GeminiConfig config,
    String text,
  ) async {
    // Voice is part of the filename: change the voice and the cached clip is
    // simply a different file, never a stale one in the wrong voice.
    final f = File('$dir/${name}_${config.voice}.pcm');
    try {
      if (await f.exists()) {
        final b = await f.readAsBytes();
        if (b.length > _rate) return b; // at least half a second of audio
      }
    } catch (_) {}

    final made = await _generate(config, text);
    if (made == null || made.isEmpty) return null;
    try {
      await f.writeAsBytes(made, flush: false);
    } catch (e) {
      debugPrint('[FALLBACK] could not cache $name: $e');
    }
    return made;
  }

  /// One-shot: open a session, ask for the line, keep the audio.
  Future<Uint8List?> _generate(GeminiConfig config, String text) async {
    if (config.apiKey.isEmpty) return null;
    final client = GeminiLiveClient(
      config: GeminiConfig(
        apiKey: config.apiKey,
        model: config.model,
        voice: config.voice,
        systemPrompt: 'You are a text-to-speech voice. Say exactly the words '
            'you are given, once, with nothing added and nothing omitted.',
      ),
    );
    final chunks = <Uint8List>[];
    final done = Completer<void>();
    StreamSubscription? audio;
    StreamSubscription? turn;
    try {
      await client.connect();
      audio = client.audioResponses.listen(chunks.add);
      turn = client.turnComplete.listen((_) {
        if (!done.isCompleted) done.complete();
      });
      client.sendText('Say exactly this, and nothing else: "$text"');
      await done.future.timeout(const Duration(seconds: 25));
    } catch (e) {
      debugPrint('[FALLBACK] generate failed: $e');
      if (chunks.isEmpty) return null;
    } finally {
      await audio?.cancel();
      await turn?.cancel();
      client.dispose();
    }
    if (chunks.isEmpty) return null;

    final total = chunks.fold<int>(0, (a, c) => a + c.length);
    final joined = Uint8List(total);
    var o = 0;
    for (final c in chunks) {
      joined.setRange(o, o + c.length, c);
      o += c.length;
    }
    return _resample24to16(joined);
  }

  Future<String?> _dir() async {
    try {
      return await _channel.invokeMethod<String>('clipsDir');
    } catch (e) {
      debugPrint('[FALLBACK] no clips dir: $e');
      return null;
    }
  }

  // ---------------------------------------------------------------- playback

  Timer? _tick;
  Uint8List? _playing;
  int _pos = 0;
  bool _loop = false;

  bool get isPlaying => _tick != null;

  /// Feed [pcm] to the board at real time.
  ///
  /// Paced rather than dumped: the writer is arrival-driven, so handing it a
  /// whole clip at once would blow past the trim threshold and most of it would
  /// be discarded as stale.
  void play(Uint8List pcm, {bool loop = false, String? what}) {
    if (pcm.isEmpty) {
      debugPrint('[FALLBACK] nothing to play${what == null ? '' : ' ($what)'}');
      return;
    }
    stop();
    if (what != null) debugPrint('[FALLBACK] playing $what');
    _playing = pcm;
    _pos = 0;
    _loop = loop;
    _tick = Timer.periodic(const Duration(milliseconds: 60), (_) => _pump());
  }

  void _pump() {
    final src = _playing;
    if (src == null) {
      stop();
      return;
    }
    if (_pos >= src.length) {
      if (!_loop) {
        stop();
        return;
      }
      _pos = 0;
    }
    final end = math.min(_pos + _frameBytes, src.length);
    bridge.sendPcm(Uint8List.fromList(src.sublist(_pos, end)));
    _pos = end;
  }

  void stop() {
    _tick?.cancel();
    _tick = null;
    _playing = null;
    _pos = 0;
    _loop = false;
  }

  /// Roughly how long [pcm] takes to play.
  static Duration lengthOf(Uint8List pcm) =>
      Duration(milliseconds: (pcm.length / 2 / _rate * 1000).round());

  void dispose() => stop();

  // --------------------------------------------------------------- synthesis

  /// A calm arpeggio that loops without a click.
  ///
  /// Each note is enveloped to silence at both ends, and the loop finishes on
  /// silence, so the join is inaudible. Kept quiet and consonant — the caller
  /// is waiting, not being entertained.
  static Uint8List _synthesiseHoldMusic() {
    const noteMs = 420;
    const gapMs = 700;
    const notes = [261.63, 329.63, 392.00, 329.63]; // C E G E
    const amp = 0.16;

    final noteSamples = _rate * noteMs ~/ 1000;
    final gapSamples = _rate * gapMs ~/ 1000;
    final total = noteSamples * notes.length + gapSamples;

    final out = Uint8List(total * 2);
    final view = ByteData.view(out.buffer);
    var i = 0;

    for (final f in notes) {
      for (var n = 0; n < noteSamples; n++) {
        final t = n / _rate;
        // Raised cosine over the whole note: zero at both ends, so notes never
        // click into each other and the loop point is silent.
        final env = 0.5 * (1 - math.cos(2 * math.pi * n / noteSamples));
        // A touch of the octave gives it body without being shrill.
        final v = math.sin(2 * math.pi * f * t) +
            0.3 * math.sin(2 * math.pi * f * 2 * t);
        view.setInt16(i * 2, (v * env * amp * 32767 / 1.3).round(), Endian.little);
        i++;
      }
    }
    // Trailing silence is already zeros.
    return out;
  }

  /// 24 kHz to 16 kHz for a complete buffer.
  ///
  /// No carried state, unlike the streaming resampler in GeminiCallAgent: this
  /// runs once over a whole clip, so there are no block boundaries to click at.
  static Uint8List _resample24to16(Uint8List input) {
    final n = input.length ~/ 2;
    if (n < 2) return Uint8List(0);
    final src = ByteData.view(input.buffer, input.offsetInBytes, n * 2);
    const step = 1.5;
    final count = ((n - 1) / step).floor();
    final out = Uint8List(count * 2);
    final view = ByteData.view(out.buffer);
    for (var o = 0; o < count; o++) {
      final pos = o * step;
      final i = pos.floor();
      final frac = pos - i;
      final a = src.getInt16(i * 2, Endian.little);
      final b = src.getInt16((i + 1) * 2, Endian.little);
      view.setInt16(
          o * 2, (a + (b - a) * frac).round().clamp(-32768, 32767), Endian.little);
    }
    return out;
  }
}
